site_name: "QFORMATPY"
site_description: "Simple Python library for fixed-point arithmetic using ARM-style Q-format notation."
site_url: https://qformatpy.readthedocs.io/en
repo_url: https://github.com/ericsmacedo/qformatpy
copyright: Copyright (c) 2024 ericsmacedo

theme:
  name: material
  palette:
    - media: "(prefes-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefes-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
    - content.code.select
    - content.code.annotate

nav:
  - Home:
      - Welcome to QFORMATPY: index.md
      - Contributing: contributing.md
  #- Usage: usage.md
  - API:
      - Overview: api.md
  - Examples:
    - "ex_integrator/ex_integrator.ipynb"

plugins:
  - search
  - mkdocs-jupyter:
      execute: true
  - include-markdown
  - autorefs
  - literate-nav:
      nav_file: README.md
      implicit_index: true
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_options:
              ignore_init_summary: true
            summary: true
            show_source: false
            unwrap_annotated: true
            members_order: source
            show_docstring_parameters: true
            show_docstring_other_parameters: true
            separate_signature: true
            signature_crossrefs: true
            show_signature_annotations: true
            show_symbol_type_heading: true
            # preload_modules: [pydantic]
            inherited_members: false
            docstring_section_style: spacy
            docstring_style: numpy
            show_signature: true
          import:
            - https://docs.python.org/3/objects.inv

markdown_extensions:
  - admonition
  - attr_list
  - mkdocs-click
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

watch:
  - src
  - CONTRIBUTING.md
